---
# get pod info from pod name
- name: Get pod info
  k8s_info:
    kubeconfig: '{{ kubeconfig }}'
    kind: Pod
    namespace: '{{ namespace_name }}'
    name: '{{ pod_name }}'
  register: pod_info


# we are getting timestamps from pod -o yaml ############################################


- name: deug multiline
  debug: msg="{{ pod_info | json_query(jmesquery) }}"
  vars:
    jmesquery: "resources[*].{CreationTime : metadata.creationTimestamp, PodScheduled : status.conditions[3].lastTransitionTime, Initialized : status.conditions[0].lastTransitionTime, ContainersReady : status.conditions[2].lastTransitionTime, Ready : status.conditions[1].lastTransitionTime}"


##########################################################################################  

- name: Get events of pod
  k8s_info:
    kubeconfig: '{{ kubeconfig }}'
    kind: Event
    namespace: '{{ namespace_name }}'
    field_selectors:
      - involvedObject.name={{ pod_name }}
  register: pod_events


# for loop to get all events of pod and set_fact only message if reason is Pulled and disable logs
- name: Get pulled events
  set_fact:
    pulled_events: "{{ pulled_events | default([]) + [item] }}"
  loop: "{{ pod_events.resources }}"
  when: item.reason == 'Pulled'
  loop_control:
    label: "{{ item.message, item.reason }}"

